site_name: OpenSpending
site_description: OpenSpending is a database for the storage and analysis of fiscal data.
site_url: https://docs.openspending.org
repo_url: https://github.com/openspending/openspending
pages:
- Home:
  - Start: index.md
- Developers:
  - 'Getting started': developers/index.md
  - Platform: developers/platform.md
  - Datastore: developers/datastore.md
  - Explorer: developers/explorer.md
  - Theming Guide: developers/theming-guide.md
  - Views: developers/views.md
  - 'Auth Client': developers/auth-client.md
  - CLI: developers/cli.md
- Contributors:
  - 'Getting started': contributors/index.md
  - Prepare: contributors/prepare.md
  - Package: contributors/package.md
  - Load: contributors/load.md
  - Use: contributors/use.md
- Users:
  - 'Getting started': users/index.md
  - Explore: users/explore.md
  - Interact: users/interact.md
  - Export: users/export.md
theme: readthedocs

